### ISSUE TITLE
Bug handling ConditionOperator.Null / NotNull

### ISSUE THREAD

**Issue by benArrayx** [jordimontana82/fake-xrm-easy#102]
I found another one ;)

```
    var account1 = new Account() { Id = Guid.NewGuid(), Name = "1 Test" };
    var account2 = new Account() { Id = Guid.NewGuid(), Name = "2 Test" };
    var account3 = new Account() { Id = Guid.NewGuid(), Name = "3 Test" };
    var account4 = new Account() { Id = Guid.NewGuid(), Name = "4 Test" };
    var account5 = new Account() { Id = Guid.NewGuid(), Name = "5 Test" };
    var account6 = new Account() { Id = Guid.NewGuid(), Name = "6 Test" };
    var account7 = new Account() { Id = Guid.NewGuid() };
    var account8 = new Account() { Id = Guid.NewGuid(), Name = "Another name" };

    List<Account> initialAccs = new List<Account>() {
        account1, account2, account3, account4, account5, account6, account7, account8
    };

    Context.Initialize(initialAccs);

    QueryExpression query = new QueryExpression()
    {
        EntityName = "account",
        ColumnSet = new ColumnSet(true),
        Conditions =
        {
            new ConditionExpression("name", ConditionOperator.Null)
        }
    };

    EntityCollection ec = Service.RetrieveMultiple(query); //throws System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=FakeXrmEasy
  StackTrace:
       at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionDefault(Expression input, Object value) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 544
       at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionBasedOnValueInherentType(Expression input, Object value) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 518
       at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionBasedOnValue(Expression input, Object value) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 489
       at FakeXrmEasy.XrmFakedContext.TranslateConditionExpressionEqual(XrmFakedContext context, ConditionExpression c, Expression getAttributeValueExpr, Expression containsAttributeExpr) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 634
       at FakeXrmEasy.XrmFakedContext.TranslateConditionExpression(XrmFakedContext context, ConditionExpression c, ParameterExpression entity) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 372
       at FakeXrmEasy.XrmFakedContext.TranslateMultipleConditionExpressions(XrmFakedContext context, List`1 conditions, LogicalOperator op, ParameterExpression entity) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 838
       at FakeXrmEasy.XrmFakedContext.TranslateFilterExpressionToExpression(XrmFakedContext context, FilterExpression fe, ParameterExpression entity) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 938
       at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionFiltersToExpression(XrmFakedContext context, QueryExpression qe, ParameterExpression entity) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 927
       at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionToLinq(XrmFakedContext context, QueryExpression qe) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.Queries.cs:line 290
       at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\FakeMessageExecutors\RetrieveMultipleRequestExecutor.cs:line 25
       at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass88_0.<FakeRetrieveMultiple>b__0(QueryBase req) in F:\Arrayx\SourceCode\dotNet\Dynamics\fake-xrm-easy\FakeXrmEasy.Shared\XrmFakedContext.cs:line 296
       at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in Z:\TeamCityAgent\work\b8aff86b339c02d7\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 105
       at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass9_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in Z:\TeamCityAgent\work\b8aff86b339c02d7\src\FakeItEasy\Configuration\RuleBuilder.cs:line 144
       at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in Z:\TeamCityAgent\work\b8aff86b339c02d7\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
       at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in Z:\TeamCityAgent\work\b8aff86b339c02d7\src\FakeItEasy\Core\FakeManager.cs:line 188
       at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in Z:\TeamCityAgent\work\b8aff86b339c02d7\src\FakeItEasy\Core\FakeManager.cs:line 144
       at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in Z:\TeamCityAgent\work\b8aff86b339c02d7\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 252
       at Castle.DynamicProxy.AbstractInvocation.Proceed() in Z:\TeamCityAgent\work\b8aff86b339c02d7\src\FakeItEasy\Core\FakeCallEqualityComparer.cs:line 0
       at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)

```
XrmFakedContext.Queries.cs: line 544

```
protected static Expression GetAppropiateCastExpressionDefault(Expression input, object value)
    {
        return Expression.Convert(input, value.GetType());  //Default type conversion
    }
```

In the case of ConditionOperator.Null or NotNull, the value itself is null.

**Comment by jordimontana82** [comment]
Thx again! :)

**Comment by jordimontana82** [comment]
Hi @benArrayx  again!

Added some commits to try to reproduce this issue, but it is working fine for me.  

Could you have a look please?

**Comment by benArrayx** [comment]
Hi Jordi, apologies, seems like this one was my bad, my code was passing null as the ConditionExpression value, when of course a Null ConditionExpression should not have a value! Sorry about that :(

**Comment by jordimontana82** [comment]
No worries... will close this one!
