### ISSUE TITLE
Retrieve Multiple FetchXml Query and "Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityReference' to type 'System.String'."

### ISSUE THREAD

**Issue by LIT2K7** [jordimontana82/fake-xrm-easy#156]
Hi

Not sure if the below bug is resolved 

https://github.com/jordimontana82/fake-xrm-easy/issues/59

but today I ran into same exact problem as mentioned in bug 59 when I used a fetchXml statement on Connection entity with a condition for a specific Record1Id.

Using FakeXrmEasy 365 / 2016

Connection Setup::
var conne = new Connection
{
Id = Guid.NewGuid(),
Record1Id = custom1.ToEntityReference(),
Record2Id = contact1.ToEntityReference(),
Record2RoleId = conRolee1.ToEntityReference(),
StateCode = 0
};

Here is the FetchXml
`<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'> <entity name='connection'> <attribute name='record2id' /> <attribute name='record2roleid' /> <attribute name='connectionid' /> <attribute name='record1id' /> <order attribute='record2id' descending='false' /> <filter type='and'> <condition attribute='record1id' operator='eq' uitype='new_custom' value= '{5d79df73-3993-4ba8-837e-d2a7307feba9}' /> <condition attribute='statecode' operator='eq' value='0' /> </filter> <link-entity name='contact' from='contactid' to='record2id' alias='ah'> <filter type='and'> <condition attribute='statecode' operator='eq' value='0' /> </filter> </link-entity> </entity> </fetch>`

The above fetchxml query generated the following error

"Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityReference' to type 'System.String'."

Exception Details:
System.InvalidCastException was unhandled by user code
HResult=-2147467262
Message=Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityReference' to type 'System.String'.
Source=Anonymously Hosted DynamicMethods Assembly
StackTrace:
at lambda_method(Closure , Entity )
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.OrderedEnumerable1.d__1.MoveNext()
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source) at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx) at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass93_0.<FakeRetrieveMultiple>b__0(QueryBase req) at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClassd2.b__c(IFakeObjectCall call)
at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass8.b__7(IInterceptedFakeObjectCall x)
at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall)
at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall)
at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IWritableFakeObjectCall fakeObjectCall)
at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation)
at Castle.DynamicProxy.AbstractInvocation.Proceed()
at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)
at CRM.Workflow.updateEmailList.Test.RunReturnConnectionListFetchXmlTest() in C:\content\playground\updateEmailList\CRM.Workflow.updateEmailList.Test\UpdateEmailListTest.cs:line 270

Please help.

Thanks

**Comment by jordimontana82** [comment]
Hi @LIT2K7 

Could you please post a full unit test to reproduce this?

Cheers!

**Comment by LIT2K7** [comment]
Thanks for getting back to me. 

Nuget package information below:

`  <package id="FakeItEasy" version="2.3.3" targetFramework="net452" />
  <package id="FakeXrmEasy.2016" version="1.24.0" targetFramework="net452" />`

Nunit Test: 

`
[Test]
        public void When_I_run_connection_fetchXml_it_should_return_matching_contact_on_record1id()
        {
            // Arrange
            // Create Contacts 
            var contact = new Entity("contact");
            contact.Id = Guid.NewGuid();
            contact.Attributes.Add("firstname", "First");
            contact.Attributes.Add("lastname", "User");
            contact.Attributes.Add("statecode", new OptionSetValue(0));

            // Create Other User
            var otherContact = new Entity("contact");
            otherContact.Id = Guid.NewGuid();
            otherContact.Attributes.Add("firstname", "Other");
            otherContact.Attributes.Add("lastname", "User");
            otherContact.Attributes.Add("statecode", new OptionSetValue(0));

            // Connection Role
            var conRole = new Entity("connectionrole");
            conRole.Id = Guid.NewGuid();
            conRole.Attributes.Add("name", "Contact");
            conRole.Attributes.Add("statecode", new OptionSetValue(0));

            // Create connection with disclosure AND CONTACT
            var conn = new Entity("connection");
            conn.Id = Guid.NewGuid();
            conn.Attributes.Add("record1id", contact.ToEntityReference()); // discloser
            conn.Attributes.Add("record2id", otherContact.ToEntityReference()); // contact
            conn.Attributes.Add("record2roleid", conRole.ToEntityReference()); // Connection Role
            conn.Attributes.Add("statecode", new OptionSetValue(0));

            // Create Faked Context
            var ctx = new XrmFakedContext();
            // ctx.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Connection));
            ctx.ProxyTypesAssembly = Assembly.GetExecutingAssembly();
            ctx.Initialize(new List<Entity>() { contact, otherContact, conRole, conn });

            // Fetch Xml
            string fetchXml = @"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                                                          <entity name='connection'>
                                                            <attribute name='record2id' />
                                                            <attribute name='record2roleid' />
                                                            <attribute name='connectionid' />
                                                            <attribute name='record1id' />
                                                            <filter type='and'>
                                                              <condition attribute='record1id' operator='eq' uitype='contact' value= '{0}' />
                                                              <condition attribute='statecode' operator='eq' value='0' />
                                                            </filter>
                                                            <link-entity name='contact' from='contactid' to='record2id' alias='ah'>
                                                              <filter type='and'>
                                                                <condition attribute='lastname' operator='not-null' />
                                                                <condition attribute='statecode' operator='eq' value='0' />
                                                              </filter>
                                                            </link-entity>
                                                          </entity>
                                                        </fetch>";
            fetchXml = string.Format(fetchXml, contact.Id);

            // Act
            EntityCollection getConnectionListResults = ctx.GetFakedOrganizationService().RetrieveMultiple(new FetchExpression(fetchXml));


            // Assert 
            Assert.True(getConnectionListResults.Entities.Count > 0);
        }
`
Stack Trace:

System.InvalidCastException was unhandled by user code
  HResult=-2147467262
  Message=Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityReference' to type 'System.String'.
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , Entity )
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
       at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass93_0.<FakeRetrieveMultiple>b__0(QueryBase req)
       at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 105
       at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass9_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 144
       at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
       at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 187
       at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
       at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 252
       at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Core\DynamicDummyFactory.cs:line 0
       at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)
       at CDP.CRM.Workflow.updateEmailList.Test.MockUnitTest.When_I_run_connection_fetchXml_it_should_return_matching_contact_on_record1id() in C:\content\playground\FakeXrm2016\CRM.Workflow.updateList\CRM.Workflow.updateList.Test\MockUnitTest.cs:line 196
  InnerException:

**Comment by jordimontana82** [comment]
Just commited an example where that test runs fine. Basically, make sure you setup the ProxyTypesAssembly correctly so that types can be used, or, just call .Initialize with early bound entities.

    ctx.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Connection));
