### ISSUE TITLE
The given key was not present in the dictionary. After update to 1.34.0

### ISSUE THREAD

**Issue by AleksandrRogov** [jordimontana82/fake-xrm-easy#226]
Hi Jordi,

All my unit tests that use FetchXml are throwing the error: The given key was not present in the dictionary.
When I added a pdb file, the original error comes from here:
![image](https://user-images.githubusercontent.com/1893650/29132394-0ec35f92-7cfe-11e7-8204-54df03e31ebb.png)

Stack Trace:
```
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Xrm.Sdk.DataCollection`2.get_Item(TKey key)
   at lambda_method(Closure , Entity )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
```
I cannot give you more info at this moment, I have to roll back to 1.33.1.

Thanks

**Comment by eNeRGy164** [comment]
Can you provide the unit test (FetchXml / entity types) you encounter the issue with so it can be reproduced?

**Comment by AleksandrRogov** [comment]
Hi,
The issue is connected to `olderthan-x-month` operator. When there is no DateTime attribute in the `Entity` object indicated in the Fetch XML and that needs to be compared. Unit test is the following:

```c#
[Fact]
public void FetchXml_Operator_Older_Than_X_Months_WithoutDateAttribute_Execution()
{
    var contact1 = new Contact
    {
        Id = Guid.NewGuid(),
        //remove it or make it null then exception "The given key was not presented in the dictionary" will be thrown
        //BirthDate = new DateTime(2017, 8, 7)
    };

    var contact2 = new Contact
    {
        Id = Guid.NewGuid(),
        BirthDate = new DateTime(2017, 3, 7)
    };

    var fetchXml = @"
                    <fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false' page='1'>
                        <entity name='contact'>
                            <attribute name='contactid' />
                            <attribute name='birthdate' />
                            <filter type='and' >
                                <condition attribute='birthdate' operator='olderthan-x-months' value='3' />
                            </filter>
                        </entity>
                    </fetch>";

    var ctx = new XrmFakedContext();
    ctx.Initialize(new Entity[] { contact1, contact2 });
    var collection = ctx.GetFakedOrganizationService().RetrieveMultiple(new FetchExpression(fetchXml));

    Assert.Equal(1, collection.Entities.Count);
}
```

There is also another issue with `olderthan-x-months` operator, I will create a ticket for it.

**Comment by AleksandrRogov** [comment]
BTW, other tests failed because "Entity sdkmessageprocessingstep does not exist in the metadata cache" which has already been reported in #227 and #229. I never generate all system entities for plugins or any other app integrated with CRM, it's always done partially, only entities that are used directly in the app.
