### ISSUE TITLE
Create Inner Calendar throws System.Exception: Entity sdkmessageprocessingstep does not exist in the metadata cache

### ISSUE THREAD

**Issue by pbolduc** [jordimontana82/fake-xrm-easy#227]
Version:
```
  <package id="FakeItEasy" version="3.2.0" targetFramework="net462" />
  <package id="FakeXrmEasy.2016" version="1.34.0" targetFramework="net462" />
```

I am trying to test the creation of calendars.  When my code goes to create a new inner calendar I get an exception:  System.Exception: Entity sdkmessageprocessingstep does not exist in the metadata cache

Here is a simple example that demonstrates the issue.  Am I doing something wrong?

```

        [TestMethod]
        public void create_calendar()
        {
            List<Entity> entities = new List<Entity>();

            entities.Add(new BusinessUnit { Id = Guid.NewGuid(), Name = "Unit Test" });
            var businessUnitReference = entities[entities.Count - 1].ToEntityReference();

            XrmFakedContext xrmContext = new XrmFakedContext();
            xrmContext.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Calendar));
            xrmContext.Initialize(entities);

            var calendar = new Calendar
            {
                BusinessUnitId = businessUnitReference,
                Type = new OptionSetValue(-1) // Inner Calendar type
            };

            var organizationService = xrmContext.GetOrganizationService();

            organizationService.Create(calendar);
        }
```

Stack Trace
```
System.Exception: Entity sdkmessageprocessingstep does not exist in the metadata cache
    at FakeXrmEasy.XrmFakedContext.EnsureEntityNameExistsInMetadata(String sEntityName)
   at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionToLinq(XrmFakedContext context, QueryExpression qe)
   at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass121_0.<FakeRetrieveMultiple>b__0(QueryBase req)
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 108
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 215
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 212
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 251
   at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
   at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)
   at FakeXrmEasy.XrmFakedContext.GetStepsForStage(String method, ProcessingStepStage stage, ProcessingStepMode mode, Entity entity)
   at FakeXrmEasy.XrmFakedContext.ExecutePipelineStage(String method, ProcessingStepStage stage, ProcessingStepMode mode, Entity entity)
   at FakeXrmEasy.XrmFakedContext.AddEntityWithDefaults(Entity e, Boolean usePluginPipeline)
   at FakeXrmEasy.XrmFakedContext.CreateEntity(Entity e, Boolean usePluginPipeline)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass38_0.<FakeCreate>b__0(Entity e)
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 108
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 215
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 212
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 251
   at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
   at Castle.Proxies.ObjectProxy.Create(Entity entity)
   at QueryCalendarTests.create_calendar() in D:\work\QueryCalendarTests.cs:line 164

**Comment by eNeRGy164** [comment]
This probably happens when you use generated classes tgat don't contain all entities

**Comment by pbolduc** [comment]
I have used our generated classes against a real CRM 2016 environment and it works.

This code works with a real IOrganizationService against CRM 2016.  Do you suggest it would work if I disabled proxy types and use late binding entities?

```
var organizationService = ...
var calendar = new Calendar {
    BusinessUnitId = businessUnitReference,
    Type = new OptionSetValue(-1) // Inner Calendar type
};

organizationService.Create(calendar);
```

**Comment by pbolduc** [comment]
This works:
```
        [TestMethod]
        public void create_calendar()
        {
            var businessUnit = new Entity("businessunit");
            businessUnit.Id = Guid.NewGuid();
            businessUnit.Attributes["name"] = "Unit Test";

            XrmFakedContext xrmContext = new XrmFakedContext();
            xrmContext.Initialize(businessUnit);


            var calendar = new Entity("calendar");
            calendar.Attributes["businessunitid"] = businessUnit.ToEntityReference();
            calendar.Attributes["type"] = new OptionSetValue(-1); // Inner Calendar type

            var organizationService = xrmContext.GetOrganizationService();

            organizationService.Create(calendar);
        }
```

**Comment by jordimontana82** [comment]
If you try with v1.33.1 does it work?

Latest version introduced an initial version of a simulated pipeline execution which I think it would be best to keep it as an optional setting enabled via app.config.

**Comment by eNeRGy164** [comment]
It should work with early bound types as long as the entities sdkmessage, plugintype, sdkmessagefilter and sdkmessageprocessingstep are available with it.

I use some custom filtering when generated early bound types to reduce the size of the generated file (and lot's of other fancy stuff) and FakeXrmEasy doesn't like it when you mix early bound and late bound in the same test. And my code uses late bound types as there are no early bound types in the framework itself.

I will rewrite my code I added for the plugin system so it doesn't use QueryExpression/RetrieveMultiple as it seems to limit the experience for end users.

**Comment by jordimontana82** [comment]
@pbolduc  Please use v1.33.1 in the meantime while this gets reviewed and fixed for the next release :)

**Comment by pbolduc** [comment]
I will give that version a try tomorrow. Now I really wish I didn't do 'reset HEAD --hard' already.

**Comment by pbolduc** [comment]
Using v1.33.1 did works around this problem thanks.

**Comment by jordimontana82** [comment]
No worries,

Quick one about early bound entities. If you pass an early bound entity to .Initialize() then there's no need to do:

   xrmContext.ProxyTypesAssembly = Assembly.GetAssembly(typeof(Calendar));

That's only needed whenever there is no call to .Initialize(), like, when your initial state / arrange phase is pretty much empty.
