### ISSUE TITLE
Error when trying to set image or partylist attribute values

### ISSUE THREAD

**Issue by parvezghumra** [jordimontana82/fake-xrm-easy#259]
Hi @jordimontana82,

I thought I should open an issue here rather than bombarding you with emails! :)

I have come across an error when I try to set the value of an image attribute or a partylist attribute in one of my unit tests. The image attribute value is set as a byte-array and the partylist attribute value is set as a collection of Entities. Here's the full stack trace for both cases.

Hope this helps.

Thanks,
Parvez

**Stack trace when attempting to set image attribute**
`Attribute type not supported when trying to clone attribute 'System.Byte[]'
   at FakeXrmEasy.Extensions.EntityExtensions.CloneAttribute(Object attributeValue)
   at FakeXrmEasy.Extensions.EntityExtensions.Clone(Entity e, Type t)
   at FakeXrmEasy.XrmFakedContext.AddEntityWithDefaults(Entity e, Boolean usePluginPipeline)
   at FakeXrmEasy.XrmFakedContext.CreateEntity(Entity e)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass44_0.<FakeCreate>b__0(Entity e)
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 108
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 215
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 211
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 251
   at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
   at Castle.Proxies.ObjectProxy.Create(Entity entity)`

**Stack trace when attempting to set partylist attribute**
`Attribute type not supported when trying to clone attribute 'Microsoft.Xrm.Sdk.Entity[]'
   at FakeXrmEasy.Extensions.EntityExtensions.CloneAttribute(Object attributeValue)
   at FakeXrmEasy.Extensions.EntityExtensions.Clone(Entity e, Type t)
   at FakeXrmEasy.XrmFakedContext.AddEntityWithDefaults(Entity e, Boolean usePluginPipeline)
   at FakeXrmEasy.XrmFakedContext.CreateEntity(Entity e)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass44_0.<FakeCreate>b__0(Entity e)
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 108
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 215
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 211
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 251
   at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
   at Castle.Proxies.ObjectProxy.Create(Entity entity)`

**Comment by jordimontana82** [comment]
Hi Parvez,

Thanks a mill for reporting this. I'll take a look, in the meantime, would be great if you could also post 2 unit tests to reproduce these, one for each.

Cheers!
