### ISSUE TITLE
AboveOrEqual in RetrieveMultiple is not implemented

### ISSUE THREAD

**Issue by slushpuppy-dev** [jordimontana82/fake-xrm-easy#287]
FakeXrmEasy.PullRequestException: 'Exception: Operator AboveOrEqual not yet implemented for condition expression. This functionality is not available yet. Please consider contributing to the following Git project https://github.com/jordimontana82/fake-xrm-easy by cloning the repository and issuing a pull request.'

FakeXrmEasy.PullRequestException
  HResult=0x80131500
  Message=Exception: Operator AboveOrEqual not yet implemented for condition expression. This functionality is not available yet. Please consider contributing to the following Git project https://github.com/jordimontana82/fake-xrm-easy by cloning the repository and issuing a pull request.
  Source=FakeXrmEasy
  StackTrace:
   at FakeXrmEasy.XrmFakedContext.TranslateConditionExpression(QueryExpression qe, XrmFakedContext context, TypedConditionExpression c, ParameterExpression entity)
   at FakeXrmEasy.XrmFakedContext.TranslateMultipleConditionExpressions(QueryExpression qe, XrmFakedContext context, String sEntityName, List`1 conditions, LogicalOperator op, ParameterExpression entity, Boolean bIsOuter)
   at FakeXrmEasy.XrmFakedContext.TranslateFilterExpressionToExpression(QueryExpression qe, XrmFakedContext context, String sEntityName, FilterExpression fe, ParameterExpression entity, Boolean bIsOuter)
   at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionFiltersToExpression(XrmFakedContext context, QueryExpression qe, ParameterExpression entity)
   at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionToLinq(XrmFakedContext context, QueryExpression qe)
   at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass131_0.<FakeRetrieveMultiple>b__0(QueryBase req)
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call)
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x)
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_5.RetrieveMultiple(QueryBase query)
   at CRMPAG.DFL.Systemuser.helper.GetHierarchicalOrganisation() in C:\Users\abachert\Source\Workspaces\DFL\Crm 2016\CRMPAG.DFL.Systemuser\CRMPAG.DFL.Systemuser\CRMPAG.DFL.Systemuser\helper.cs:line 38
   at CRMPAG.DFL.Systemuser.OnChangeOrganisationUpdateSystemuser.ExecuteCrmPlugin(LocalPluginContext localContext) in C:\Users\abachert\Source\Workspaces\DFL\Crm 2016\CRMPAG.DFL.Systemuser\CRMPAG.DFL.Systemuser\CRMPAG.DFL.Systemuser\OnChangeOrganisationUpdateSystemuser.cs:line 73
   at CRMPAG.DFL.Systemuser.PluginBase.Execute(IServiceProvider serviceProvider) in C:\Users\abachert\Source\Workspaces\DFL\Crm 2016\CRMPAG.DFL.Systemuser\CRMPAG.DFL.Systemuser\CRMPAG.DFL.Systemuser\PluginBase.cs:line 159
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass158_0`1.<ExecutePluginWith>b__0(IServiceProvider provider)
   at FakeItEasy.CallbackConfigurationExtensions.<>c__DisplayClass2_0`2.<Invokes>b__0(IFakeObjectCall call)
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_1.Execute(IServiceProvider serviceProvider)
   at FakeXrmEasy.XrmFakedContext.ExecutePluginWith[T](XrmFakedPluginExecutionContext ctx, T instance)
   at FakeXrmEasy.XrmFakedContext.ExecutePluginWith[T](XrmFakedPluginExecutionContext ctx)
   at CRMPAG.DFL.Systemuser_TestProject.Program.Main(String[] args) in C:\Users\abachert\Source\Workspaces\DFL\Crm 2016\CRMPAG.DFL.Systemuser\CRMPAG.DFL.Systemuser\CRMPAG.DFL.Systemuser_TestProject\Program.cs:line 37

**Comment by jordimontana82** [comment]
Hi @slushpuppy-dev , thx for raising this.

FakeXrmEasy does not support hierachy operators yet. This is one of the in progress tasks. Maybe you'd like to contribute and add them?

https://github.com/jordimontana82/fake-xrm-easy/blob/1a305b8cd9c35d3d77e21b00282be566b48d0a09/FakeXrmEasy.Tests.Shared/FakeContextTests/FetchXml/ConditionOperatorTests.cs#L19-L110

**Comment by PowerPlatformProfessor** [comment]
I will give it a shot to try and solve this in upcoming weeks

**Comment by AhmedMunawar** [comment]
Hi, @jordimontana82 @PowerPlatformProfessor Is this missing operator support already implemented ?
I am also facing errors in "above", "above or equal" operators

**Comment by jordimontana82** [comment]
Hi @AhmedMunawar , none of the hierarchy operators are supported as of now. If there is huge demand for this I'll add it to the backlog after  v2 is out. Unless you'd like to take a look and submit a PR?
