### ISSUE TITLE
Error "Entity [...] does not exist in the metadata cache" testing a plugin with a call to a "GetRelatedManyToManyEntities" method on a custom N:N relationship

### ISSUE THREAD

**Issue by rpothin** [jordimontana82/fake-xrm-easy#317]
Hi everyone,

I need your help on this, after 2 days trying to find a solution.
I am trying to test a plugin that verifiy the presence of partners (account records) for an account where the condition "Direct Client" is checked, and throw an error if it is not the case (below the method used for that).

```
private void CheckPartnerAccountsIfAccountNotCLientDirect(Entity entity, IOrganizationService service, ITracingService tracingService)
{
    var accountTargetImage = entity.ToEntity<Account>();

    if (accountTargetImage.ClientDirect != null)
    {
        if (accountTargetImage.ClientDirect.Value == false)
        {
            var partnerAccountsList = accountTargetImage.GetAccountPartners(service, "accountid");
            // Stop the save process if there is no partnerAccount related to the target
            if (partnerAccountsList.Count == 0)
                throw new InvalidPluginExecutionException("Error Message");
        }
    }
}
```

The method "GetAccountPartners" in the code above has been generated with XrmToolKit (you can find a part of the code below).

```
public List<Account> GetAccountPartners (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedManyToManyEntities<Account>(Service, this, "account", "accountid", "account", "accountid", "new_account_partnetaccount", "accountidone", "accountidtwo", Columns); }

[...]

public static List<Entity> GetRelatedManyToManyEntities(IOrganizationService service, BaseProxyClass proxy, string linkFromEntityTypeName, string linkFromAttributeName, string linkToEntityTypeName, string linkToAttributeName, string intermediateEntityName, string intermediateFromAttributeName, string intermediateToAttributeName, ColumnSet columns)
{
    var query = new QueryExpression()
    {
        EntityName = linkToEntityTypeName,
        ColumnSet = columns,
        LinkEntities = {
            new LinkEntity(){
                LinkFromAttributeName = linkToAttributeName,
                LinkFromEntityName = linkToEntityTypeName,
                LinkToAttributeName = intermediateToAttributeName,
                LinkToEntityName = intermediateEntityName,
                LinkEntities = {
                    new LinkEntity(){
                        LinkFromAttributeName = intermediateFromAttributeName,
                        LinkFromEntityName = intermediateEntityName,
                        LinkToAttributeName = linkFromAttributeName,
                        LinkToEntityName = linkFromEntityTypeName,
                        LinkCriteria = new FilterExpression(){
                            Conditions = {
                                new ConditionExpression(linkFromAttributeName, ConditionOperator.Equal, new object[]{ proxy.Id })
                            }
                        }
                    }
                }
            }
        }
    };

    return service.RetrieveMultiple(query).Entities.ToList();
}
```

I prepared the test below:

```
[Fact]
public void Test()
{
    // Variables declaration
    var fakeCrmContext = new XrmFakedContext();
    var fakeOrganizationService = fakeCrmContext.GetFakedOrganizationService();

    var account = new Account();
    var partner = new Account();

    XrmFakedRelationship fakeRelationship = new XrmFakedRelationship();
    EntityReference entityReference = new EntityReference();
    EntityReferenceCollection relatedEntities = new EntityReferenceCollection();
    Relationship relationship = new Relationship("new_account_partnetaccount");

    ParameterCollection inputParameters = new ParameterCollection();
    var pluginContext = fakeCrmContext.GetDefaultPluginContext();

    // Customization of the account used for the test
    account.Id = Guid.NewGuid();
    account["name"] = "Test AccountPlugins Account";
    account["new_clientdirect"] = false;

    // Customization of the partner used for the test
    partner.Id = Guid.NewGuid();
    partner["name"] = "Test AccountPlugins Partner";
    
    fakeOrganizationService.Create(account);
    fakeOrganizationService.Create(partner);

    // Creation of the relationship Account-Partner
    fakeRelationship.IntersectEntity = "account";
    fakeRelationship.Entity1LogicalName = Account.GetLogicalName();
    fakeRelationship.Entity1Attribute = "accountid";
    fakeRelationship.Entity2LogicalName = Account.GetLogicalName();
    fakeRelationship.Entity2Attribute = "name";
    fakeRelationship.RelationshipType = 0;
    fakeCrmContext.AddRelationship("new_account_partnetaccount", fakeRelationship);

    entityReference.LogicalName = Account.GetLogicalName();
    entityReference.Id = partner.Id;
    relatedEntities.Add(entityReference);

    var associateRequest = new AssociateRequest
    {
        Relationship = relationship,
        Target = account.ToEntityReference(),
        RelatedEntities = relatedEntities
    };

    fakeOrganizationService.Execute(associateRequest);

    // Adding of the account to the input parameters for the plugin call
    inputParameters.Add("Target", account);

    // Preparation of the plugin context
    pluginContext.Stage = 40;
    pluginContext.MessageName = "Update";
    pluginContext.InputParameters = inputParameters;

    // Plugin call
    var result = Record.Exception(() => fakeCrmContext.ExecutePluginWithConfigurations<AccountPlugins>(pluginContext, null, null));

    // Unit test result
    Assert.Null(result);
}
```

But, I always get the following error:

```
Actual:   System.Exception: Entity new_account_partnetaccount does not exist in the metadata cache
             at FakeXrmEasy.XrmFakedContext.EnsureEntityNameExistsInMetadata(String sEntityName)
             at FakeXrmEasy.XrmFakedContext.TranslateLinkedEntityToLinq(XrmFakedContext context, LinkEntity le, IQueryable`1 query, ColumnSet previousColumnSet, Dictionary`2 linkedEntities, String linkFromAlias, String linkFromEntity)
             at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionToLinq(XrmFakedContext context, QueryExpression qe)
             at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
             at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass137_0.<FakeRetrieveMultiple>b__1(QueryBase req)
             at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 108
             at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 215
             at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
             at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 211
             at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
             at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 251
             at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
             at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)
			 [...]
```
			 
I do not know if the fact that it is a N:N custom relationship could be the origin of the issue.

Thank you in advance for your help on this and have a nice day.

Regards,
Raphael

**Comment by rpothin** [comment]
Hello everyone,

I am really sorry.
I just needed few more time to figure out the origin of my issue.

I just had to add the proxy class dedicated to my custom N:N relationship through XrmToolKit.

Again really sorry if someone has began to look at my problem.

Have a nice day.
Raphael
