### ISSUE TITLE
"Invalid character specified for alias" exception when using '.'

### ISSUE THREAD

**Issue by AlexeiPoplutin** [jordimontana82/fake-xrm-easy#403]
Hi,

I'm getting "Invalid character specified for alias" exception when using '.' symbol in entity alias. Example: 
EntityAlias = "Connection.modifiedby"

But this works fine with real CRM. Tested at v9.1. So I believe regexp should be updated.

Thanks!

**Comment by jordimontana82** [comment]
Hi @AlexeiPoplutin , could you please post the stack trace or a unit test as an example?

It would greatly help speeding up issue resolution by the community.

Thanks!

**Comment by AlexeiPoplutin** [comment]
Hi Jordi, sorry for the delay in response.
Here is the stack trace:
`   at FakeXrmEasy.XrmFakedContext.TranslateLinkedEntityToLinq(XrmFakedContext context, LinkEntity le, IQueryable`1 query, ColumnSet previousColumnSet, Dictionary`2 linkedEntities, String linkFromAlias, String linkFromEntity)
   at FakeXrmEasy.XrmFakedContext.TranslateLinkedEntityToLinq(XrmFakedContext context, LinkEntity le, IQueryable`1 query, ColumnSet previousColumnSet, Dictionary`2 linkedEntities, String linkFromAlias, String linkFromEntity)
   at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionToLinq(XrmFakedContext context, QueryExpression qe)
   at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass151_0.<FakeRetrieveMultiple>b__1(QueryBase req)
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 108
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 215
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 211
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 251
   at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
   at Castle.Proxies.ObjectProxy_4.RetrieveMultiple(QueryBase query)
   at .Plugins.Repositories.XrmRepository.GetCrmContact(Guid contactId) in \Repositories\XrmRepository.cs:line 179
   at .ExecuteLogic(IOrganizationService service, ITracingService tracer, Entity entity, String messageName) in D:\Projects\myplugin.cs:line 147
   at Plugins.IntegrationWith.Execute(IServiceProvider serviceProvider) in D:\Projects\myplugin.cs:line 62`

The test is pretty simple:
`public void Contact_Created_FakedContext()
        {
            var fakedContext = new XrmFakedContext();

            var guid1 = Guid.NewGuid();
            var target = new Entity("contact") { Id = guid1 };

            var plugin = new IntegrationWith();

            var inputParams = new ParameterCollection { new KeyValuePair<string, object>("Target", target) };

            //Execute our plugin against the selected target
            var plugCtx = fakedContext.GetDefaultPluginContext();
            plugCtx.InputParameters = inputParams;

            fakedContext.ExecutePluginWith(plugCtx, plugin);
        }`

The error message I found just in one place in the code in file XrmFakedContext.Queries.cs, method TranslateLinkedEntityToLinq()


Thanks!

**Comment by jordimontana82** [comment]
@AlexeiPoplutin  this has been merged. Will be pushed later on today along with other updates.
