### ISSUE TITLE
QueryByAttribute - cant search by null value

### ISSUE THREAD

**Issue by czart8** [jordimontana82/fake-xrm-easy#404]
I can't search by null value. It works directly in CRM, but in test I get:

System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
     at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionDefault(Expression input, Object value)
     at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionBasedOnValueInherentType(Expression input, Object value)
     at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionBasedOnAttributeTypeOrValue(Expression input, Object value, Type attributeType)
     at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionBasedOnType(Type t, Expression input, Object value)
     at FakeXrmEasy.XrmFakedContext.TranslateConditionExpressionEqual(XrmFakedContext context, TypedConditionExpression c, Expression getAttributeValueExpr, Expression containsAttributeExpr)
     at FakeXrmEasy.XrmFakedContext.TranslateConditionExpression(QueryExpression qe, XrmFakedContext context, TypedConditionExpression c, ParameterExpression entity)
     at FakeXrmEasy.XrmFakedContext.TranslateMultipleConditionExpressions(QueryExpression qe, XrmFakedContext context, String sEntityName, List`1 conditions, LogicalOperator op, ParameterExpression entity, Boolean bIsOuter)
     at FakeXrmEasy.XrmFakedContext.TranslateFilterExpressionToExpression(QueryExpression qe, XrmFakedContext context, String sEntityName, FilterExpression fe, ParameterExpression entity, Boolean bIsOuter)
     at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionFiltersToExpression(XrmFakedContext context, QueryExpression qe, ParameterExpression entity)
     at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionToLinq(XrmFakedContext context, QueryExpression qe)
     at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
     at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass149_0.<FakeRetrieveMultiple>b__1(QueryBase req)

**Comment by BetimBeja** [comment]
Hello,
I guess you are using late bound, a unit test to reproduce the problem would be helpful.
You cannot find the correct type on null values without metadata, or Early Bound entities...
Best regards,
Betim.

**Comment by BetimBeja** [comment]
Hello @czart8 ,
do you have any feedback about this issue?

**Comment by czart8** [comment]
Hello @BetimBeja,
Thanks for the info. I've changed implementation, now I use Early Bound entities and problem is solved.
