### ISSUE TITLE
Getting Object null exception when use OptionsetValueCollection

### ISSUE THREAD

**Issue by sarul84** [jordimontana82/fake-xrm-easy#450]
Hi,
I am getting the below error when I try to do unit test my custom workflow. I am using the latest stable version.

Exception: Object reference not set to an instance of an object.

```
at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionDefault(Expression input, Object value)
   at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionBasedOnValueInherentType(Expression input, Object value)
   at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionBasedOnAttributeTypeOrValue(Expression input, Object value, Type attributeType)
   at FakeXrmEasy.XrmFakedContext.GetAppropiateCastExpressionBasedOnType(Type t, Expression input, Object value)
   at FakeXrmEasy.XrmFakedContext.TranslateConditionExpressionContainValues(TypedConditionExpression tc, Expression getAttributeValueExpr, Expression containsAttributeExpr)
   at FakeXrmEasy.XrmFakedContext.TranslateConditionExpression(QueryExpression qe, XrmFakedContext context, TypedConditionExpression c, ParameterExpression entity)
   at FakeXrmEasy.XrmFakedContext.TranslateMultipleConditionExpressions(QueryExpression qe, XrmFakedContext context, String sEntityName, List`1 conditions, LogicalOperator op, ParameterExpression entity, Boolean bIsOuter)
   at FakeXrmEasy.XrmFakedContext.TranslateFilterExpressionToExpression(QueryExpression qe, XrmFakedContext context, String sEntityName, FilterExpression fe, ParameterExpression entity, Boolean bIsOuter)
   at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionFiltersToExpression(XrmFakedContext context, QueryExpression qe, ParameterExpression entity)
   at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionToLinq(XrmFakedContext context, QueryExpression qe)
   at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass151_0.<FakeRetrieveMultiple>b__1(QueryBase req)
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass5_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.cs:line 108
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass16_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall x) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 215
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 108
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 211
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 144
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 251
   at Castle.DynamicProxy.AbstractInvocation.Proceed() in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 0
   at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)
   at Workflows.Test.SkillsWorkflowTest.CheckSkillWorkflow_AccountService() in C:\monorepo\Workflows.Test\SkillsWorkflow.Test.cs:line 49
```
Please find below test method:

```

public void CheckSkillWorkflow_AccountService()
        {
            var fakedContext = new XrmFakedContext();

            var moveMoney = new EntityReference(CrmEntities.CaseCategory.CategoryName) { Id = Guid.NewGuid(), Name = "MoveMoney" };
            
            var skillRef1 = new EntityReference("new_skill", Guid.NewGuid());
            var skill1 = new Entity(CrmEntities.Skill.EntityName, skillRef1.Id);
            skill1.Attributes.Add("new_brand", "Test");
            skill1.Attributes.Add("new_casecategory", moveMoney);
            skill1.Attributes.Add("new_skillname", "Skill1");
            skill1.Attributes.Add("new_state", new OptionSetValueCollection() { new OptionSetValue(1700010) });

            var service = fakedContext.GetOrganizationService();
            service.Create(skill1);

            QueryExpression skillQuery = new QueryExpression
            {
                EntityName = "new_skill",
                ColumnSet = new ColumnSet("new_skillname")
            };

            //skillQuery.Criteria = new FilterExpression();

            skillQuery.Criteria.AddCondition(new ConditionExpression("new_casecategory", ConditionOperator.Equal, moveMoney.Id));
            skillQuery.Criteria.AddCondition(new ConditionExpression("new_brand", ConditionOperator.In, "Test"));
            skillQuery.Criteria.AddCondition(new ConditionExpression("new_state", ConditionOperator.ContainValues, new int[] { 1700010 }));


            try
            {
                var entities = service.RetrieveMultiple(skillQuery).Entities;
            }
            catch (Exception ex)
            {
                throw;
            }
        }
```

**Comment by sarul84** [comment]
Hi, I figured out what caused this issue. The framework expects poco class for the entity that has multi select option set.
