### ISSUE TITLE
FindReflectedAttributeType Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ioanacro** [jordimontana82/fake-xrm-easy#560]
Hi,
I have this test that is joining Account entity with my custom entity Project. When I add a condition on account I get 
**Object reference not set to an instance of an object.** error in FakeXrmEasy.XrmFakedContext.FindReflectedAttributeType
when calling RetrieveMultiple method.

        [Test]
        public void TestStandardEntities()
        {
            this.context = new XrmFakedContext();
            var accountId = Guid.NewGuid();
            var AccountToBeFound = new Account { Id = accountId, Name = "TestAccount", AccountId = accountId };

            var ProjectToBeFound = new project
            {
                name = "TestProject",
                projectId = Guid.NewGuid(),
                projectcode = "someCode",
                accountid = AccountToBeFound.ToEntityReference()
            };

            this.context.Initialize(new List<Entity> { AccountToBeFound, ProjectToBeFound });

            this.service = this.context.GetOrganizationService();

            var xml = @"<fetch count='10' distinct='true' page='1'>
                                <entity name='project'>
                                    <attribute name='projectid' />
                                       <filter type='or'>
                                             <condition entityname='account' attribute='name' operator='like' value='TestAccount%' />
                                       </filter>
                                    <link-entity name='account' from='accountid' to='accountid'>
                                    </link-entity>
                                </entity>
                             </fetch>";

            var response = this.service.RetrieveMultiple(new FetchExpression(xml));

            response.Entities.Count().Should().Be(1);
        }

This query is working fine on the real CRM database. What object is null in this case? 

Using 1.57.0.0 version

Another thing I noticed is if I change my condition to use another account attribute
 <condition entityname='account' attribute='**accountratingcode**' operator='eq' value='1' />
then I get System.Exception : XrmFakedContext.FindReflectedAttributeType: Attribute accountratingcode not found for type ...Models.project

Looks like the library is looking in my custom entity for those attributes.

**Comment by jordimontana82** [comment]
Hi, latest version is 1.57.1, not sure if you tried that one and have the same issue there?

**Comment by jordimontana82** [comment]
Also, could you check if the new attribute was generated (assuming you're generating early bound entities with crmsvcutil?)

**Comment by jordimontana82** [comment]
Thanks @ioanacro ,

If you could please post the entire stack trace and the generated entities involved in this test, so the community might help? Otherwise it's going to be very difficult to reproduce.

Thanks!

**Comment by ioanacro** [comment]
Hi @jordimontana82 ,

[ProjectTest.txt](https://github.com/jordimontana82/fake-xrm-easy/files/6558799/ProjectTest.txt)
[Competitor.txt](https://github.com/jordimontana82/fake-xrm-easy/files/6558801/Competitor.txt)
[test.txt](https://github.com/jordimontana82/fake-xrm-easy/files/6558803/test.txt)

I've attached the generated entities, I used new ones only for testing purposes.

My guess from the 2 errors above is that earlyBoundType in FindReflectedAttributeType is wfp_ProjectClass instead of Competitor and propertyInfo ends up being null since everything is substracted from attributeName="name".

This is the stack trace:
System.NullReferenceException : Object reference not set to an instance of an object.
   at FakeXrmEasy.XrmFakedContext.FindReflectedAttributeType(Type earlyBoundType, String sEntityName, String attributeName)
   at FakeXrmEasy.Extensions.FetchXml.XmlExtensionsForFetchXml.GetConditionExpressionValueCast(String value, XrmFakedContext ctx, String sEntityName, String sAttributeName, ConditionOperator op)
   at FakeXrmEasy.Extensions.FetchXml.XmlExtensionsForFetchXml.ToConditionExpression(XElement elem, XrmFakedContext ctx)
   at FakeXrmEasy.Extensions.FetchXml.XmlExtensionsForFetchXml.<>c__DisplayClass21_0.<ToFilterExpression>b__3(XElement el)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FakeXrmEasy.Extensions.FetchXml.XmlExtensionsForFetchXml.ToFilterExpression(XElement elem, XrmFakedContext ctx)
   at FakeXrmEasy.Extensions.FetchXml.XmlExtensionsForFetchXml.<>c__DisplayClass16_0.<ToCriteria>b__1(XElement el)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at FakeXrmEasy.Extensions.FetchXml.XmlExtensionsForFetchXml.ToCriteria(XDocument xlDoc, XrmFakedContext ctx)
   at FakeXrmEasy.XrmFakedContext.TranslateFetchXmlDocumentToQueryExpression(XrmFakedContext context, XDocument xlDoc)
   at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass155_0.<FakeRetrieveMultiple>b__0(QueryBase req)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass155_0.<FakeRetrieveMultiple>b__2(QueryBase req)
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 97
   at FakeItEasy.Core.FakeManager.ApplyBestRule(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 261
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(InterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 173
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)

**Comment by jordimontana82** [comment]
In the FetchXml attached it seems you are trying to retrieve an attribute using the name of the entity instead of the attribute name:

<attribute name='{wfp_ProjectTest.EntityLogicalName}' />

Could you remove this bit to see if that works?

**Comment by jordimontana82** [comment]
![imagen](https://user-images.githubusercontent.com/3968950/120084596-d1790800-c0d1-11eb-9b9f-06fad56adb54.png)

**Comment by ioanacro** [comment]
> ou are trying to retrieve an attribute using the name of the entity instead of the attribute name:

Hey, 
I still get 'Object reference not set to an instance of an object.'  error with that line fixed or removed

**Comment by BetimBeja** [comment]
```csharp
[Test]
public void TestStandardEntities()
{
	this.context = new XrmFakedContext();
	var accountId = Guid.NewGuid();
	var competitor = new Competitor { Id = accountId, Name = "something to look for" };

	var project = new wfp_ProjectTest
	{
		wfp_Competitor = competitor.ToEntityReference(),
		wfp_ProjectTestId = Guid.NewGuid()
	};

	this.context.Initialize(new List<Entity> { competitor, project });

	this.service = this.context.GetOrganizationService();

	var xml = $@"<fetch top='50' >
				  <entity name='{wfp_ProjectTest.EntityLogicalName}' >
					<attribute name='{wfp_ProjectTest.EntityLogicalName}' />
					<filter>
					  <condition entityname='{Competitor.EntityLogicalName}' attribute='name' operator='like' value='%something%' />
					</filter>
					<link-entity name='competitor' from='competitorid' to='wfp_appointment' />
				  </entity>

				  <entity name='{wfp_ProjectTest.EntityLogicalName}' >
					<attribute name='{wfp_ProjectTest.Fields.wfp_ProjectTestId}' />
					<filter>
					  <condition entityname='{Competitor.EntityLogicalName}' attribute='{Competitor.Fields.Name}' operator='like' value='%something%' />
					</filter>
					<link-entity name='{Competitor.EntityLogicalName}' from='{Competitor.Fields.CompetitorId}' to='{wfp_ProjectTest.Fields.wfp_Competitor}' />
				  </entity>
				</fetch>";

	var response = this.service.RetrieveMultiple(new FetchExpression(xml));

	response.Entities.Count().Should().Be(1);
}
```
I don't think that specifying twice your `entity` node in the FetchXML is supported in FakeXrmEasy

**Comment by jordimontana82** [comment]
Good spot @BetimBeja  That wasn't in the orignal bug at the top and I missed it @ioanacro . 

Is that supported in the FetchXml schema even? I never seen a fetchXml with two entity nodes myself....

**Comment by BetimBeja** [comment]
@jordimontana82 i think I found the bug. 
https://github.com/jordimontana82/fake-xrm-easy/blob/f294b9af7319f8e23d4032a9290ec75a628f2435/FakeXrmEasy.Shared/XrmFakedContext.Queries.cs#L183-L194 here in this part there is a check, if the string ends with name, which is valid because it is looking for the name property, but it doesn't find it in the `wfp_ProjectTest` entity and throws with a null reference in [this](https://github.com/jordimontana82/fake-xrm-easy/blob/f294b9af7319f8e23d4032a9290ec75a628f2435/FakeXrmEasy.Shared/XrmFakedContext.Queries.cs#L189) line

**Comment by ioanacro** [comment]
> @jordimontana82 I think I found the bug.
> https://github.com/jordimontana82/fake-xrm-easy/blob/f294b9af7319f8e23d4032a9290ec75a628f2435/FakeXrmEasy.Shared/XrmFakedContext.Queries.cs#L183-L194
> 
> here in this part, there is a check, if the string ends with name, which is valid because it is looking for the name property, but it doesn't find it in the `wfp_ProjectTest` entity and throws with a null reference in [this](https://github.com/jordimontana82/fake-xrm-easy/blob/f294b9af7319f8e23d4032a9290ec75a628f2435/FakeXrmEasy.Shared/XrmFakedContext.Queries.cs#L189) line

Hi @BetimBeja,

But why it looks in wfp_projectTest for the attribute name? the condition is on Competitor:
<condition entityname='{Competitor.EntityLogicalName}' attribute='{Competitor.Fields.Name}'...>

**Comment by dkanaev** [comment]
I faced the same problem, in my case, the problem is in this line
![image](https://user-images.githubusercontent.com/5987954/133208113-00068352-119b-4787-8fe4-01e30b0d785e.png)

**Comment by BetimBeja** [comment]
![image](https://user-images.githubusercontent.com/11160171/133213128-7aa0ee61-7ba4-464f-8c5d-160b0a39d496.png)
https://docs.microsoft.com/en-us/dotnet/api/system.type.basetype?view=net-5.0#remarks
I think you are creating Early Bound Entities with `object` returning properties...

**Comment by dkanaev** [comment]
@BetimBeja yes, I created  Early Bound Entities. But, it is not an object type.

 [AttributeLogicalName("rr_unitcategories")]
 public virtual IEnumerable<rr_UnitCategories> rr_UnitCategories { get; set; }
 
This value was autogenerated for multi-select optionset  value

**Comment by BetimBeja** [comment]
the next paragraph tells you that the same is valid for Interfaces too
![image](https://user-images.githubusercontent.com/11160171/133223083-ddc78abd-097d-49fa-9626-be4457812a2b.png)
What is the benefit of having the IEnumerable<T> instead of a concrete class in this particular case?

**Comment by dkanaev** [comment]
The point is I use RR.DLaB.Xrm.EarlyBoundGenerator to generate this code and at the moment I did not find how to configure it for generating class instead of interface

**Comment by jordimontana82** [comment]
@ioanacro Which early bound generator did you use? Just to check if it's really the same issue...

**Comment by ioanacro** [comment]
Hey, I'm also using EarlyBoundGenerator
