### ISSUE TITLE
BUG: FakedOrganizationService().RetrieveMultiple by FetchXml

### ISSUE THREAD

**Issue by phuocle** [jordimontana82/fake-xrm-easy#59]
I Initialize code

            var context = new XrmFakedContext();
            var accountId = Guid.NewGuid();
            var license1 = new Entity("pl_license");
            license1.Id = Guid.NewGuid();
            license1.Attributes["pl_no"] = 1;
            license1.Attributes["pl_accountid"] = new EntityReference("account", accountId);

            var license2 = new Entity("pl_license");
            license2.Id = Guid.NewGuid();
            license2.Attributes["pl_no"] = 2;
            license2.Attributes["pl_accountid"] = new EntityReference("account", accountId);

            context.Initialize(new List<Entity> { license1, license2 });

Write a unit test by **QueryExpression** and **test passed**

            var query = new QueryExpression();
            query.EntityName = "pl_license";
            query.ColumnSet = new ColumnSet("pl_no");
            query.Criteria.AddCondition("pl_accountid", ConditionOperator.Equal, accountId);
            var rows = context.GetFakedOrganizationService().RetrieveMultiple(query);
            Assert.Equal(rows.Entities.Count, 2);

And write unit test by **FetchXml** and **test failed**

            var fetchXml =
              "<fetch>" +
              "  <entity name='pl_license'>" +
              "     <attribute name='pl_no'/>" +
              "     <filter type='and'>" +
              "         <condition attribute='pl_accountid' operator='eq' value='{0}' />" +
              "     </filter>" +
              "  </entity>" +
              "</fetch>";
            fetchXml = string.Format(fetchXml, accountId);
            var rows = context.GetFakedOrganizationService().RetrieveMultiple(new FetchExpression(fetchXml));
            Assert.Equal(rows.Entities.Count, 2);

I get an Exception when **RetrieveMultiple**

`Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityReference' to type 'System.String'.`

Now I change the code to

`license1.Attributes["pl_accountid"] = accountId.ToString();`
`license2.Attributes["pl_accountid"] = accountId.ToString();`

And the unit test **FetchXml passed**. 

> This changed code INVALID for late bound, because pl_accountid is a lookup to Account entity

Our project use a lot of FetchXml when retrieve data. Please double check.

Thanks

**Comment by jordimontana82** [comment]
Hey @phuocle 

This is fixed now.

Will push a newer version as soon as I fix other bugs.

Cheers,

**Comment by LIT2K7** [comment]
Hi 

I ran into the same exact problem as mentioned above when I used a fetchXml statement on Connection entity with a condition for a specific Record1Id. 

Using FakeXrmEasy 365

Connection Setup::
var conne = new Connection 
{ 
	Id = Guid.NewGuid(), 
	Record1Id = custom1.ToEntityReference(), 
	Record2Id = contact1.ToEntityReference(), 
	Record2RoleId = conRolee1.ToEntityReference(), 
	StateCode = 0 
};

Here is the FetchXml
<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
  <entity name='connection'>
	<attribute name='record2id' />
	<attribute name='record2roleid' />
	<attribute name='connectionid' />
	<attribute name='record1id' />
	<order attribute='record2id' descending='false' />
	<filter type='and'>
	  <condition attribute='record1id' operator='eq' uitype='new_custom' value= '{5d79df73-3993-4ba8-837e-d2a7307feba9}' />
	  <condition attribute='statecode' operator='eq' value='0' />
	</filter>
	<link-entity name='contact' from='contactid' to='record2id' alias='ah'>
	  <filter type='and'>
		<condition attribute='statecode' operator='eq' value='0' />
	  </filter>
	</link-entity>
  </entity>
</fetch>

The above generated the following error 

"Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityReference' to type 'System.String'."

Exception Details:
System.InvalidCastException was unhandled by user code
  HResult=-2147467262
  Message=Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityReference' to type 'System.String'.
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , Entity )
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
       at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass93_0.<FakeRetrieveMultiple>b__0(QueryBase req)
       at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClassd`2.<ReturnsLazily>b__c(IFakeObjectCall call)
       at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass8.<ReturnsLazily>b__7(IInterceptedFakeObjectCall x)
       at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall)
       at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall)
       at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IWritableFakeObjectCall fakeObjectCall)
       at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation)
       at Castle.DynamicProxy.AbstractInvocation.Proceed()
       at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)
       at CRM.Workflow.updateEmailList.Test.RunReturnConnectionListFetchXmlTest() in C:\content\playground\updateEmailList\CRM.Workflow.updateEmailList.Test\UpdateEmailListTest.cs:line 270

Note: This works fine when I use LINQ query but generates an exception with fetchXml query.

Please check.

Thanks
