### ISSUE TITLE
FetchXml with the linked query fails with a NullReferenceException.

### ISSUE THREAD

**Issue by krishire** [jordimontana82/fake-xrm-easy#70]
StackTrace:   

at FakeXrmEasy.XrmFakedContext.TranslateLinkedEntityFilterExpressionToExpression(LinkEntity le, ParameterExpression entity)
   at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionFiltersToExpression(QueryExpression qe, ParameterExpression entity)
   at FakeXrmEasy.XrmFakedContext.TranslateQueryExpressionToLinq(XrmFakedContext context, QueryExpression qe)
   at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)

fetchXml =
 
```
"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
  <entity name='systemuser'>
    <attribute name='fullname' />
     <attribute name='systemuserid' />
     <attribute name='businessunitid' />
     <filter type='and'>
      <condition attribute='systemuserid' operator='eq' uitype='systemuser' value='#userId#' />
     </filter>
        <link-entity name='businessunit' from='businessunitid' to='businessunitid' alias='bu' intersect='true' >
            <attribute name='name' />
        </link-entity>
  </entity>
</fetch>"
```
 
Code: var UserRequest = new RetrieveMultipleRequest { Query = new FetchExpression(fetchXml.Replace("#userId#",context.InitiatingUserId.ToString())) };
                var UserResponseCoreObject = ((RetrieveMultipleResponse)service.Execute(UserRequest )).EntityCollection.Entities[0];  //Failed Code ((RetrieveMultipleResponse)service.Execute(UserRequest ))

**Comment by krishire** [comment]
Updating the Fetchxml with a filter criteria (shown below) to overcome the error above,
          ```
<link-entity name='businessunit' from='businessunitid' to='businessunitid' alias='bu' intersect='true' >
            <attribute name='rbsm_defaultcontactrole' />
           <filter type='and'>
                <condition attribute='name' operator='eq'  value='#Name#' />
            </filter>
</link-entity>
```
Ending up with the following error: Collection was modified; enumeration operation may not execute.

Stack Trace:  at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at FakeXrmEasy.Extensions.EntityExtensions.JoinAttributes(Entity e, Entity otherEntity, ColumnSet columnSet, String alias, XrmFakedContext context)
   at lambda_method(Closure , Entity , Entity )
   at System.Linq.Enumerable.<JoinIterator>d__61`4.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
   at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass59_0.<FakeExecute>b__0(OrganizationRequest req)
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClassd`2.<ReturnsLazily>b__c(IFakeObjectCall call)
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass8.<ReturnsLazily>b__7(IInterceptedFakeObjectCall x)
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Core.FakeManager.ApplyRule(CallRuleMetadata rule, IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IWritableFakeObjectCall fakeObjectCall)

**Comment by jordimontana82** [comment]
Hi @krishire 

Could you please provide the entire unit test? I'd like to know what entities / input are you using in your test (ones passed to the .Initialize()).

Cheers,

**Comment by krishire** [comment]
Jordi,
He is on holiday for two weeks, I'm waiting for him to come back this
Monday, I will update you as soon as I talk to him.
Thanks,
Krish

**Comment by krishire** [comment]
```
public void FirstCodeActivityTest()
        { 
            var fakedContext = new XrmFakedContext {};

            var fakedWorkflowContext = fakedContext.GetDefaultWorkflowContext(); 

            fakedContext.ProxyTypesAssembly = Assembly.GetAssembly(typeof(BusinessUnit));  

            var entityAccount = new Account { Id = Guid.NewGuid(), Name = "My First Faked Account yeah!", LogicalName = "account" };
            var entityContact = new Contact { Id = Guid.NewGuid(),ParentCustomerId = entityAccount.ToEntityReference() };
            
            var entityBusinessUnit = new BusinessUnit {   Name="TestBU", BusinessUnitId = Guid.NewGuid() };  

            var initiatingUser = new SystemUser
            {
                Id = fakedWorkflowContext.InitiatingUserId,
                FirstName = "TestUser",
                DomainName = "TestDomain", 
                BusinessUnitId = entityBusinessUnit.ToEntityReference() 
            }; 

            fakedContext.Initialize(new List<Entity>() {
               entityBusinessUnit,entityAccount,entityContact,initiatingUser
            });

            fakedWorkflowContext.PrimaryEntityName = "contact";
            fakedWorkflowContext.PrimaryEntityId = entityContact.Id;

            var fakedActivity = fakedContext.ExecuteCodeActivity(fakedWorkflowContext, new Dictionary<string, object>(), new TestCodeActivity());

            //Assert that the target contains a new attribute
            

        }
```

**Comment by krishire** [comment]
though the fetchxml expression is executed successfully, still not able to use the linked entity attribute in this fashion

sourcedByResponseCoreObject.GetAttributeValue<AliasedValue>("bu.name").Value

**Comment by krishire** [comment]
jordi,

Though the fetchxml expression is executed successfully, still not able to
use the linked entity attribute in this fashion

UserResponseCoreObject.GetAttributeValue("bu.name").Value


Am I missing something.


Thanks,

Krish.

**Comment by krishire** [comment]
Very much thankful to you.

Regards,
Krish.

**Comment by jordimontana82** [comment]
Hi @krishire 

Thanks for spotting that. 

There is a step to translate the FetchXml query into a QueryExpression, which is then executed, and that one was generating the LinkTo attribute with the LinkFrom and the LinkFrom with the LinkTo attributes, so they were swapped. That was fixed in this commit.

The FetchXml query execution still needs some tweaking, cause it is more recent than QueryExpressions and LINQ implementations so please do let me know if you are still having issues like this one.

Regards,
