### ISSUE TITLE
QuoteProduct(quotedetail) FetchXml Test Help

### ISSUE THREAD

**Issue by donamk** [jordimontana82/fake-xrm-easy#99]
Hello,

I am hard to test the following FetchXml query.

```
[Fact]
public void Query_Should_Return_QuoteProduct_Counts()
{
    var context = new XrmFakedContext();
    context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(QuoteProduct));


    var quoteId = Guid.NewGuid();

    context.Initialize(new List<Entity>()
    {
        new QuoteProduct()
        {
            Id = Guid.NewGuid(),
            ExistingProduct = new EntityReference("product", Guid.NewGuid()),
            Quantity = 4M,
            Quote = new EntityReference("quote", quoteId)
        }
    });

    IOrganizationService service = context.GetFakedOrganizationService();

    string fetchXml =
        $@"<fetch aggregate='true' >
                <entity name='quotedetail' >
                <attribute name='productid' alias='ProductCount' aggregate='count' />
                <filter>
                    <condition attribute='quoteid' operator='eq' value='{quoteId}' />
                </filter>
                </entity>
            </fetch>";

    EntityCollection collection = service.RetrieveMultiple(new FetchExpression(fetchXml));


    Assert.Equal(1, collection.Entities.Count);
}
```

When I test the test, I got the following Error

```
Exception Message:
At least some node is not valid
Stacktrace:
 at FakeXrmEasy.XrmFakedContext.TranslateFetchXmlDocumentToQueryExpression(XrmFakedContext context, XDocument xlDoc)
 at FakeXrmEasy.FakeMessageExecutors.RetrieveMultipleRequestExecutor.Execute(OrganizationRequest req, XrmFakedContext ctx)
 at FakeXrmEasy.XrmFakedContext.<>c__DisplayClass88_0.<FakeRetrieveMultiple>b__0(QueryBase req)
 at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass8.<ReturnsLazily>b__7(IInterceptedFakeObjectCall x)
 at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall)
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IWritableFakeObjectCall fakeObjectCall)
 at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy.RetrieveMultiple(QueryBase query)
 at DiamondICT.Plugins.Sandboxed.UnitTests.QueryHelperTests.HasQuoteProducts_Should_Return_True_When_Quote_Has_Product() 
```

I assume that QuoteProduct something not valid however I am bit hard to find what it is.

I tried to find which attributes need more so I made the following code.

```
var context = new XrmFakedContext();
context.ProxyTypesAssembly = Assembly.GetAssembly(typeof(QuoteProduct));

var quoteId = Guid.NewGuid();

var quoteProduct = new QuoteProduct()
{
    ExistingProduct = new EntityReference("product", Guid.NewGuid()),
    Quantity = 4M,
    Quote = new EntityReference("quote", quoteId),
    Amount = 100.00M,
    CostPerUnit = 120.00M
};

IOrganizationService service = context.GetFakedOrganizationService();

var Id = service.Create(quoteProduct);

Assert.NotNull(Id);
```

However, the QuoteProduct create test code works well.

Could you help me to test the fetchxml query?

Kindly regards,

**Comment by jordimontana82** [comment]
Hi @donamk ,

It looks like it is an issue with the FetchXml aggregation implementation. That implementation is still in progress in the backlog and it might not be complete yet.

The error is raised inside this function which validates if all the nodes in the FetchXml are valid, based on the current implementation (i.e., nodes like 'entity', 'attribute', 'condition', etc).

Could you maybe debug it and see what node is raising the exception [here](https://github.com/jordimontana82/fake-xrm-easy/blob/9842f3011b66d0bf5b305d519e48b306e6ffd5d1/FakeXrmEasy.Shared/Extensions/XmlExtensionsForFetchXml.cs#L28-L64)?

Thanks!

**Comment by donamk** [comment]
Hi @jordimontana82 

I debug with the FetchXml Query and found the error point.
As you mentioned IsFetchXmlNodeValid is the right place.

Current situation FakeXrmEasy accept filter must have type attribute.
but the condition is single type attribute can omit because it is not required 'and' or 'or' type

I don't know this is bug or intended behaviour.

```
// in IsFetchXmlNodeValid method
case "filter":
    return elem.GetAttribute("type") != null;

// the query
 string fetchXml =
        $@"<fetch aggregate='true' >
                <entity name='quotedetail' >
                <attribute name='productid' alias='ProductCount' aggregate='count' />
                <filter>
                    <condition attribute='quoteid' operator='eq' value='{quoteId}' />
                </filter>
                </entity>
            </fetch>";
```

Anyway, I can keep writing my unit test code with filter type attribute.

Thank you

**Comment by jordimontana82** [comment]
Right! Ok yeah... I we could change it to not force to have a "type" attribute for the "filter" node, and assume to use "and" if none was passed.

In the meantime yeah, just pass the "type" attribute while we fix this :)
